apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: rlt-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts: {{ range .Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rlt
spec:
  hosts: {{ range .Values.ingress.hosts }}
  - {{ . }}
  {{- end }}
  gateways:
  - rlt-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: rlt
        port:
          number: 80